build_root:
  image_stream_tag:
    name: release
    namespace: openshift
    tag: rhel-8-release-golang-1.20-openshift-4.14
images:
- dockerfile_literal: |
    FROM registry.access.redhat.com/ubi8/ubi
    RUN yum install -y podman
    WORKDIR /
    COPY --from=src /plugins /plugins
    COPY --from=src /hack/yamllint.sh /hack/yamllint.sh
  from: src
  to: krew-yaml-lint
promotion:
  name: "4.14"
  namespace: ocp
releases:
  initial:
    integration:
      name: "4.14"
      namespace: ocp
  latest:
    integration:
      include_built_images: true
      name: "4.14"
      namespace: ocp
resources:
  '*':
    limits:
      memory: 4Gi
    requests:
      cpu: 100m
      memory: 200Mi
tests:
- as: yamllint
  commands: |
    ./hack/yamllint.sh
  container:
    from: krew-yaml-lint
zz_generated_metadata:
  branch: main
  org: openshift
  repo: krew-index
