approve:
- commandHelpLink: ""
  repos:
  - openshift/krew-index
  require_self_approval: false
lgtm:
- repos:
  - openshift/krew-index
  review_acts_as_lgtm: true
plugins:
  openshift/krew-index:
    plugins:
    - approve
